spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./var/h2/customer # (1)
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: validate # (2)
  thymeleaf.cache: false
server.port: 6060
  